In [1]:
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np

def main():
    img = cv.imread('images/football.jpg',1)
    img = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
    
    w,h = img.shape
    total_size  = w*h
    print(total_size)
    
    
    th = 210
    max_val = 1    
    
    ret,out1 = cv.threshold(img,th,max_val,cv.THRESH_BINARY_INV)
    print(out1)
    
    white_size = cv.sumElems(out1)
    
    print(white_size[0])
    
    
    object_size = total_size - white_size[0]
    
    print(object_size)
    
    images = [img,out1]
    titles = ['Original','Binary']
    
    for i in range(len(images)):      
        plt.subplot(2,3,i+1)
        plt.imshow(images[i], cmap='gray')
        plt.xticks([])
        plt.yticks([])
        plt.title(titles[i])
    plt.show()

if __name__ == "__main__":
    main()

172550
[[0 0 0 ... 0 0 0]
 [0 0 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]
 ...
 [0 0 1 ... 1 1 1]
 [0 0 1 ... 1 1 1]
 [0 0 1 ... 1 1 0]]
168181.0
4369.0


<Figure size 640x480 with 2 Axes>