In [1]:
import cv2 as cv


def main():
    img = cv.imread('images/lena_color_512.tif',1)
    
    print("--------------")
    print(type(img))
    print("--------------")
    print(img.dtype)
    print("--------------")    
    print(img.shape)
    print("--------------")
    print(img.ndim)
    print("--------------")
    print(img.size)
    print("--------------")
    print(img)

    
    cv.waitKey(0)
    cv.destroyAllWindows()
    
    
if __name__ == "__main__":
    main()

--------------
<class 'numpy.ndarray'>
--------------
uint8
--------------
(512, 512, 3)
--------------
3
--------------
786432
--------------
[[[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 [[125 137 226]
  [125 137 226]
  [133 137 223]
  ...
  [122 148 230]
  [110 130 221]
  [ 90  99 200]]

 ...

 [[ 60  18  84]
  [ 60  18  84]
  [ 58  27  92]
  ...
  [ 84  73 173]
  [ 76  68 172]
  [ 79  62 177]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]

 [[ 57  22  82]
  [ 57  22  82]
  [ 62  32  96]
  ...
  [ 79  70 179]
  [ 81  71 181]
  [ 81  74 185]]]
