sci kit learn ဆိုတာ google summer project ကနေ ပေါ်ပေါက်လာတဲ့ machine learning library တစ်ခုဖြစ်ပါတယ်။ သူ့မှာ data set loading,
processing matrix နဲ့ ml algorithm အများစုပါဝင်ပြီးသားဖြစ်ပါတယ်။ code line အနည်းငယ်ရေးရုံနဲ့ အသုံးပြုလို့ရပါတယ်။ ဒီနည်းလမ်းကို သုံးရင် ml algorithm တွေရဲ့ ရလာဒ်ကို လွယ်လွယ်ကူကူ မြင်သာစေမှာဖြစ်ပါတယ်။ 
    ဥပမာကြည့်ရအောင် zoo ထဲက animals ၁၀၁ မျိုးရဲ့ data set က archive/zoo.csv မှာပါ။ သူ့ကို classify လုပ်ပေးရမှာက ပုံစံ ၇ မျိုးပါ။
    သူ့ရဲ့ attribute နဲ့ value type တွေက ဒီလိုပါ။ final ကော်လံက class_type ဆိုတာ ကျတော်တို့ စိတ်ဝင်စားတဲ့ အဖြေပါ။

In [1]:
from sklearn import svm
import pandas as pd
import math

In [ ]:
data = pd.read_csv('archive/zoo.csv')
data.head(6)

In [ ]:
data ကို training လုပ်ဖို့နဲ့ evalaute ( testing ) လုပ်ဖို့ ခွဲပေးရာမှာ sklearn မသုံးရင် ဒီလို ရေးရမှာပါ။

In [ ]:
# Shuffle and split the dataset
# We don't need to use this any more

data = data.sample(frac=1).reset_index(drop=True)
data_total_len = data[data.columns[0]].size

data_train_frac = 0.6
split_index = math.floor(data_total_len*data_train_frac)

train_data = data.iloc[:split_index]
eval_data  = data.iloc[split_index:]


In [ ]:
sklearn သုံးပြီး အောက်ပါအတိုင်း အတိုချုံးရေးလို့ရပါတယ်။ ပထမ feature သက်သက် label သက်သက်ခွဲပါမယ်။ နောက် training နဲ့ testing ခွဲပါမယ်။

In [ ]:
from sklearn.model_selection import train_test_split

all_x = data.iloc[:, 1:17] # all rows, features only, no labels
all_y = data.iloc[:,17]    # all rows, label only, no features

x_train, x_test, y_train, y_test = train_test_split(all_x, all_y)

In [ ]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

In [ ]:
svm မသုံးပဲ တခြား ml algorithm သုံးလည်းရပါတယ်။ ပြီးရင် fit method နဲ့ train ပေးပါမယ်။

In [ ]:
clf = svm.SVC()
clf.fit(x_train, y_train)


In [ ]:
model ရဲ့ performance ကို evalute လုပ်ဖို့ score() နဲ့ စမ်းနိုင်ပါတယ်။

In [ ]:
clf.score(x_test, y_test)


In [ ]:
ပြီးရင်တော့ predict လုပ်ပြီး testing data ကိုခန့်မှန်းပါမယ်။

In [ ]:
clf.predict(x_test[10:15])


In [ ]:
အဖြေတိုက်ကြည့်ဖို့ testing ကို စစ်ဆေးရင် အဖြေတူပါတယ်။

In [ ]:
# show what the correct answer is
y_test[10:15]

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split
X, y = np.arange(10).reshape((5, 2)), range(5)
print(X)
list(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


[0, 1, 2, 3, 4]

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [5]:
X_train

array([[4, 5],
       [0, 1],
       [6, 7]])

In [6]:
y_train

[2, 0, 3]

In [7]:
X_test

array([[2, 3],
       [8, 9]])

In [8]:
y_test

[1, 4]