In [2]:
import cv2 as cv
import numpy as np

def main():
    img = np.zeros((512,512,3),np.uint8)  
    
    
    cv.rectangle(img,(40,60),(80,100),(0,255,0),2)
    
    
    cv.circle(img,(150,150),10,(0,0,255),-1)
    
    cv.ellipse(img,(200,200),(50,20),0,0,360,(250,0,0),-1)
    
    points = np.array([ [10,20],[30,67],[45,97],[90,100],[200,350],[67,88],[80,90],[250,40],[24,300],[99,55] ], np.int32)
    print(points)
    points = points.reshape( (-1,1,2) )
    print(points)
    
    cv.polylines(img,[points],True,(0,255,0))
    
    text = 'ROM Robotics'
    cv.putText(img,text,(100,400),cv.FONT_HERSHEY_SIMPLEX,1.2,(255,255,0))
    
    cv.imshow('Black', img)
    cv.waitKey(0)
    cv.destroyAllWindows()
    
    
    
if __name__ == "__main__":
    main()

[[ 10  20]
 [ 30  67]
 [ 45  97]
 [ 90 100]
 [200 350]
 [ 67  88]
 [ 80  90]
 [250  40]
 [ 24 300]
 [ 99  55]]
[[[ 10  20]]

 [[ 30  67]]

 [[ 45  97]]

 [[ 90 100]]

 [[200 350]]

 [[ 67  88]]

 [[ 80  90]]

 [[250  40]]

 [[ 24 300]]

 [[ 99  55]]]


ellipse မှာ 0,0,360 ဆိုတာက ပထမ 0 သည် center က နေ spin ဖြစ်မည့် degree ဖြစ်ပီး နောက် 0 နဲ့ 90 သည် ellipse ထဲက ပေါင်းသွား သို့မဟုတ် နှုတ်သွားမဲ့ degree ဖြစ်ပါတယ်။

In [ ]:
np.reshape()

In [ ]:
cv.polylines မှာ points ဆိုရင် point တွေကို နေရာချထားပေးမှာဖြစ်သလို [points] ဆိုရင်တော့ point တွေကို ဆက်ဆွဲပေးမှာပါ။